/*
 * FILE: ui_events.c
 * AUTHOR: User
 * DESCRIPTION: User-defined event handlers. This file is generated by the
 *              tool and should be used to implement the logic for UI events.
 *              It will not be overwritten if it already exists.
 */

#include "ui.h"
// ============================== Encoder ==============================
static RotarySwitch rs(ENC_PIN_A, ENC_PIN_B, ENC_PIN_SW);
static long lastPosShown = LONG_MIN;

void on_rolType_Clicked(lv_event_t *e) {
  if (on_click_rolType)
    on_click_rolType(e);
}

void on_rolType_Focused(lv_event_t *e) {
  // Your code here
}

void on_rolType_ValueChanged(lv_event_t *e) {
  if (on_change_rolType)
    on_change_rolType(e);
}

void on_bntStart_Clicked(lv_event_t *e) {
  if (on_click_btnStart)
    on_click_btnStart(e);
}

void on_bntStart_Focused(lv_event_t *e) {
  // Your code here
}

void on_bntCancel_Focused(lv_event_t *e) {
  // Your code here
}

void on_bntCancel_Clicked(lv_event_t *e) {
  if (on_click_btnCancel)
    on_click_btnCancel(e);
}

void on_spnTimeHH_Clicked(lv_event_t *e) {
  if (on_click_timeHH)
    on_click_timeHH(e);
}

void on_spnTimeMM_ValueChanged(lv_event_t *e) {
  if (on_change_timeMM)
    on_change_timeMM(e);
}

void on_spnTimeHH_ValueChanged(lv_event_t *e) {
  if (on_change_timeHH)
    on_change_timeHH(e);
}

void on_spnTimeSS_ValueChanged(lv_event_t *e) {
  if (on_change_timeSS)
    on_change_timeSS(e);
}

void ui_event_init() {

  // RotarySwitch: stabile Parameter
  rs.begin(true);
  rs.setDebounceMs(15);
  rs.setDoubleClickWindowMs(300);
  rs.setLongClickMs(1500);
  rs.setStep(1);
  rs.setReverseDirection(false); // CW = positiv
  rs.setButtonActiveLow(false);  // dein Board: pressed = HIGH
}

void ui_event_task() {
  rs.update();

  // 1) intent-first -
  if (rs.wasDoubleClicked()) {
    Serial.println("DoubleClick");
  } else if (rs.wasLongClicked()) {
    Serial.println("LongClick");
  } else if (rs.wasShortClicked()) {
    Serial.println("ShortClick");
  }

  long newPos;
  if (rs.pollPositionChange(newPos)) {
    if (newPos != lastPosShown) {
      lastPosShown = newPos;
    }
    int8_t step = (newPos > lastPosShown) ? +1 : -1;
    // apply_step_to_focus(step);
    Serial.printf("ENC: %d\n", (int)newPos);
  }
}